version: "3"
   
services:
  nginx:
    image: nginx:alpine
    ports:
       - 8001:81
    # directorios para el archivo de configuración y archivos del static
    volumes:
       - ./conf:/etc/nginx/conf.d
       - ./static:/var/www/static 
    depends_on:
       - web
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code

    depends_on:
      - mongo
    ports:
      - 80:80

  mongo:
    image: mongo:4.2
    # ports: 
    #   - 27017:27017
    volumes:
      - ./datos_db:/data/db
      # - ./dump:/dump # para hacer restore de la bd

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on: 
      - mongo
